services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: always
    environment:
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    depends_on:
      - mongo
    ports:
      - "9090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb_container
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - app_network
volumes:
  mongo_data:
    driver: local
  redis-data:
    driver: local
networks:
  app_network:
    driver: bridge