services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mongo_network
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    depends_on:
      - mongo
    ports:
      - "9090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb_container
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - mongo_network
volumes:
  mongo_data:
    driver: local
networks:
  mongo_network:
    driver: bridge